//declarative
pipeline {
	agent any
	stages{
		stage('Build'){
			steps
			{
			  echo "Build"
			}
		}
		stage('Test'){
			steps{
				echo "Test"
			}
		}
		stage ('Deploy') {
			steps {
				echo "Deploy"
			}
		}
	}
	post{
		always {
			echo "i am awesome"
		}
		success {
			echo "i was success when you are success"
		}
		failure {
			echo "i was failure when you are failed"
		}
	}
}
