//declarative
pipeline {
	agent any
	//agent { docker { image 'mvn:13.8'}}
	//agent { docker { image 'node:13.8'} }
	stages{
		stage('Build'){
			steps
			{
			  //sh 'mvn --version'
			 // sh 'node --version'
			  echo "Build"
			  echo "PATH - $PATH"
			  echo "BUILD_NUMBER-$env.BUILD_NUMBER"
			  echo "BUILD_ID- $env.BUILD_ID"
			  echo "JOB_NAME - $env.JOB_NAME"
			  echo "BUILD_TAG - $env.BUILD_TAG"
			  echo "BUILD_URL - $env.BUILD_URL"
			}
		}
		stage('Test'){
			steps{
				echo "Test"
			}
		}
		stage ('Deploy') {
			steps {
				echo "Deploy"
			}
		}
	}
	post{
		always {
			echo "i am awesome"
		}
		success {
			echo "i was success when you are success"
		}
		failure {
			echo "i was failure when you are failed"
		}
	}
}
